main: de.instantskillz.challengeplugin.Main.Main
version: 1.0
name: InstantSkillzTV

commands:
   heal:
      description: Dieses Kommando heilt dich!
   kit:
      description: Oeffnet das Kit-Inventar!
   setspawn:
      description: Setze deinen individuellen Spawnpunkt!
   hub:
      description: Teleportiert dich zu deinem Spawnpunkt!
   chatclear:
      description: Chatverlauf loeschen.
   mute:
      description: Mute andere Spieler.
   inv:
      description: Speichere/Lade dein Inventar!
   bp:
      description: Oeffnet das Backpack!
   timer:
      description: Startet den Timer!
   gm:
      description: Aendert deinen Spielmodus!
   startbingo:
      description: Startet eine Welt mit dem Bingo-Spielmodus!
   stopbingo:
      description: Loescht die Welt mit dem Bingo-Spielmodus!
   bingo:
      description: Startet Bingo!
   pos:
      description: Speichert deine Position mit einem Namen!
   pause:
      description: Pausiere eine bestimmte Challenge!
   unpause:
      description: Spiele eine bestimmte Challenge weiter!